[toolchain]

[workspace]
members = ["programs/*"]

[features]
resolution = true
skip-lint = false

[programs.localnet]
subservice = "EvHqnZaXDeqTVSgmtFqjVEUhTchtZAiUXi8gme7juq58"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
